<a href="https://colab.research.google.com/github/mhaletoki/MA22C025_2023_PL/blob/main/Assignments/Assignment_4/numpyblitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math

In [ ]:
A = [0.1, 1.3, 0.4, 0.5] # list
a = np.array(A) # numpy array
type(a), type(A)

(numpy.ndarray, list)

In [ ]:
a.dtype # a's common element type (A.dtype is undefined!)

dtype('float64')

In [ ]:
2*a

array([0.2, 2.6, 0.8, 1. ])

In [ ]:
2*A

[0.1, 1.3, 0.4, 0.5, 0.1, 1.3, 0.4, 0.5]

In [ ]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [ ]:
 # list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]
# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)

51.5 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.43 ms ± 715 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
def f(v): # apply f to one scalar value v
  return math.sin(v) * math.exp(-v)

In [ ]:
vectorizedf = map(f, x) # apply same f to a vector of values x

In [ ]:
F = np.vectorize(f) # F can be applied to a array x

In [ ]:
#use map
%timeit y = list(map(f, x))
# use numpy's vectorize
%timeit y = F(x)
# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

42.5 ms ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
35.7 ms ± 544 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.62 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit for x in range(1000000): x**3
%timeit for x in np.arange(1000000): x**3

472 ms ± 129 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
152 ms ± 38.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.random.randint(0,9,5)#to generate a random number
a

array([3, 8, 3, 0, 7])

In [ ]:
a[::]

array([3, 8, 3, 0, 7])

In [ ]:
a[-3:]

array([3, 0, 7])

In [ ]:
a[-1], a[len(a)-1]

(7, 7)

In [ ]:
a[-4:-1:2]

array([8, 0])

In [ ]:
slice = range(-4,-1,2) # Think of b:e:s specification as a range.
a[-4:-1:2], a[slice] # In older versions, a[slice] may not work
# but will work with slice=arange(-4,-1,2).

(array([8, 0]), array([8, 0]))

In [ ]:
a = np.array([1,2,3])
b = np.array([3,4,5,6])

In [ ]:
a = b #After assigning a to b by =

a[0] = 1
a

array([1, 4, 5, 6])

In [ ]:
b #revised value

array([1, 4, 5, 6])

In [ ]:
a = np.array([1,2,3]) # This is Object1 and "a" is a name for it.
b = np.array([3,4,5,6]) # This is Object2 and "b" is a name for it.

In [ ]:
id(a), id(b) #"=" can change names but not memory contents

(136600622768720, 136600622767472)

In [ ]:
a = b # a is no longer a name for Object1, it is now a name for Object2.


In [ ]:
id(a), id(b)

(136600622767472, 136600622767472)

In [ ]:
#for copying data
a = np.array([1,2,3]) # Object1
b = np.array([3,4,5,6]) # Object2
a = b.copy() # Copies Object2, and binds a to the copy
a[0] = 2 # Only the copied (new) object is changed

In [ ]:
a, b

(array([2, 4, 5, 6]), array([3, 4, 5, 6]))

In [ ]:
Amat = [[1,2],
[3,4]]
Amat

[[1, 2], [3, 4]]

In [ ]:
amat = np.array(Amat)
amat

array([[1, 2],
       [3, 4]])

In [ ]:
type(A), type(a)

(list, numpy.ndarray)

In [ ]:
2*Amat #multiplying a list


[[1, 2], [3, 4], [1, 2], [3, 4]]

In [ ]:
2*amat #numpy array

array([[2, 4],
       [6, 8]])

In [ ]:
amat

array([[1, 2],
       [3, 4]])

In [ ]:
amat * amat #multiplying matrix

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]


In [ ]:
amat @ amat #@ for matrix multiplication

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.dot(amat, amat) # dot(A,B) = matrix A multiplied by matrix B

array([[ 7, 10],
       [15, 22]])

In [ ]:
amat.dot(amat)

array([[ 7, 10],
       [15, 22]])

In [ ]:
amat**2 # not equal to matrix power !!

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
np.linalg.matrix_power(amat, 2)

array([[ 7, 10],
       [15, 22]])

In [ ]:
A = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]]) #slicing for 2-D
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [ ]:
A[1, :], A[:, 2]

(array([2, 5, 5, 2]), array([5, 5, 8]))

In [ ]:
A[:3:2, :3]

array([[7, 8, 5],
       [9, 6, 8]])

In [ ]:
M = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]]) #storing arrays in numpy
M

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [ ]:
M.reshape(2, 6) # Just a different view of the same data

array([[7, 8, 5, 1, 2, 5],
       [5, 2, 9, 6, 8, 9]])

In [ ]:
M.ravel() # The 1D data of M in row-major ordering

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [ ]:
A = np.array(M, order='F') # storing array in Fortran’s column-major ordering.
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [ ]:
A.ravel(order='A') # A's internal ordering is Fortran style

array([7, 2, 9, 8, 5, 6, 5, 5, 8, 1, 2, 9])

In [ ]:
M.ravel(order='A') # M's internal ordering is default C-style

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [ ]:
N = np.arange(25).reshape(5,5)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
mask = (N>7) & (N<18)#masking
mask

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [ ]:
N[mask]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
#specifying locations in masking
i, j = np.where(mask) # Returns i and j indices where mask[i,j] is True.
i, j # 1st True value of mask is at i[0],j[0],
# 2nd True value of mask is at i[1],j[1], etc

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3]), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2]))

In [ ]:
data = np.random.randint(low=0, high=10, size=30) # 1D array

In [ ]:
T2 = np.reshape(data, (6, 5)) # 2D array
T2

array([[5, 9, 3, 8, 7],
       [8, 3, 7, 0, 8],
       [5, 8, 5, 4, 7],
       [3, 5, 1, 7, 9],
       [2, 9, 8, 2, 9],
       [3, 1, 5, 2, 0]])

In [ ]:
T3 = np.reshape(data, (2, 3, 5)) # 3D array
T3

array([[[5, 9, 3, 8, 7],
        [8, 3, 7, 0, 8],
        [5, 8, 5, 4, 7]],

       [[3, 5, 1, 7, 9],
        [2, 9, 8, 2, 9],
        [3, 1, 5, 2, 0]]])

In [ ]:
print('T3 is a ', T3.ndim, 'dimensional array of shape ', T3.shape)
print('T2 is a ', T2.ndim, 'dimensional array of shape ', T2.shape)
print('data is a ', data.ndim, 'dimensional array of shape ', data.shape)

T3 is a  3 dimensional array of shape  (2, 3, 5)
T2 is a  2 dimensional array of shape  (6, 5)
data is a  1 dimensional array of shape  (30,)
