<a href="https://colab.research.google.com/github/mhaletoki/MA22C025_2023_PL/blob/main/Assignments/Assignment_6/pairwise_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.random.rand(5) #generate five random numbers
print(x)


[0.84985192 0.35110388 0.58649204 0.25635226 0.07495677]


In [ ]:
D = np.subtract.outer(x, x) #calculates the pairwise differences between elements of the array

print(D)


[[ 0.          0.49874804  0.26335988  0.59349966  0.77489515]
 [-0.49874804  0.         -0.23538816  0.09475162  0.27614711]
 [-0.26335988  0.23538816  0.          0.33013978  0.51153527]
 [-0.59349966 -0.09475162 -0.33013978  0.          0.18139549]
 [-0.77489515 -0.27614711 -0.51153527 -0.18139549  0.        ]]
