<a href="https://colab.research.google.com/github/mhaletoki/MA22C025_2023_PL/blob/main/Assignments/Assignment_8/Colspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

**Basis of the column space by SVD**

In [2]:
U, S, VT = np.linalg.svd(A)

In [3]:
U

array([[-2.66235859e-01, -1.70641342e-01,  9.48683298e-01],
       [-5.39615303e-01,  8.41911709e-01, -5.55111512e-17],
       [ 7.98707576e-01,  5.11924025e-01,  3.16227766e-01]])

In [4]:
S

array([1.78088115e+01, 4.22448020e+00, 3.71370969e-16])

In [5]:
VT

array([[-0.21009764,  0.42019527, -0.72119431,  0.50909104],
       [-0.0053474 ,  0.01069481,  0.58183848,  0.81321646],
       [-0.24209024, -0.89711712, -0.29564648,  0.22173486],
       [ 0.9472184 , -0.13602362, -0.23224108,  0.17418081]])

In [6]:
rank = np.sum(S > 1e-5)
column_basis = U[:, :rank]


In [7]:
dimension = rank

In [8]:
print("Column Basis:")
print(column_basis)


Column Basis:
[[-0.26623586 -0.17064134]
 [-0.5396153   0.84191171]
 [ 0.79870758  0.51192403]]


In [9]:
print("Dimension of A=",dimension)

Dimension of A= 2


**Basis of the column space by QR Method**

In [10]:
Q,R=qr(A)

In [11]:
Q

array([[-0.26726124,  0.95618289, -0.11952286],
       [-0.53452248, -0.04390192,  0.84401323],
       [ 0.80178373,  0.28945968,  0.52283453]])

In [12]:
R

array([[-3.74165739e+00,  7.48331477e+00, -1.28285396e+01,
         9.08688223e+00],
       [ 0.00000000e+00, -1.98602732e-15, -1.31705767e-01,
        -1.75607689e-01],
       [ 0.00000000e+00,  0.00000000e+00,  2.53203970e+00,
         3.37605293e+00]])

In [13]:
rank_A = np.linalg.matrix_rank(A)

basis_columns = Q[:, :rank_A]



In [14]:
print("Basis for the column space of A:")
print(basis_columns)

Basis for the column space of A:
[[-0.26726124  0.95618289]
 [-0.53452248 -0.04390192]
 [ 0.80178373  0.28945968]]


In [15]:
print("Rank of A=:", rank_A)

Rank of A=: 2


**Checking which method is faster**

In [17]:
import time
%timeit U,S,VT=svd(A)

15 µs ± 5.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
%timeit Q,R=qr(A)

19.8 µs ± 2.45 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


*Since a smaller execution time is faster, svd is faster than qr in terms of mean execution time.*