<a href="https://colab.research.google.com/github/mhaletoki/MA22C025_2023_PL/blob/main/Assignments/Assignment_8/Nullspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],[4, 1, 9, 1, -9]])
A

array([[ 1, -2,  9,  5,  4],
       [ 1, -1,  6,  5, -3],
       [-2,  0, -6,  1, -2],
       [ 4,  1,  9,  1, -9]])

In [3]:
np.linalg.matrix_rank(A)

3

In [19]:
S,V,D=svd(A)

In [20]:
V

array([1.72083086e+01, 1.01450209e+01, 4.99526437e+00, 9.56282692e-16])

In [21]:
D.T

array([[ 0.24638127, -0.12991821,  0.3027347 , -0.87219483,  0.26466093],
       [-0.04503456, -0.20626881,  0.2022255 ,  0.3573579 ,  0.8870317 ],
       [ 0.8742475 ,  0.22905181,  0.3015276 ,  0.29073161, -0.08822031],
       [ 0.30107333,  0.27058334, -0.84037193, -0.14709627,  0.32905504],
       [-0.28690474,  0.90271499,  0.26516538, -0.07354813,  0.16452752]])

In [32]:
S

array([[ 0.49757508,  0.7203398 , -0.10593353,  0.47149517],
       [ 0.45925383,  0.0094069 , -0.61812163, -0.63790523],
       [-0.28261724, -0.26114496, -0.75778526,  0.52696519],
       [ 0.67943539, -0.64251489,  0.18018112,  0.30508511]])

In [34]:
u1,R1 = qr(A)

In [35]:
u,R1=qr(A.T)

In [36]:
u

array([[-0.08873565, -0.07763996, -0.39411774,  0.57324869, -0.70862908],
       [ 0.1774713 , -0.01770736, -0.2316473 ,  0.68751498,  0.6647203 ],
       [-0.79862086, -0.1797978 , -0.48741131, -0.1910829 ,  0.23620969],
       [-0.44367825, -0.3881998 ,  0.72286651,  0.36021819, -0.01254537],
       [-0.3549426 ,  0.90035112,  0.17579809,  0.18010909, -0.00627268]])

In [24]:
R1

array([[-1.12694277e+01, -6.21149557e+00,  5.23540341e+00,
        -4.61425385e+00],
       [ 0.00000000e+00, -5.78077182e+00, -9.54835308e-01,
        -1.04378074e+01],
       [ 0.00000000e+00,  0.00000000e+00,  4.08397364e+00,
        -7.05413629e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.39728491e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [40]:
checknull=np.array([[ 0.30107333,  0.27058334, -0.84037193, -0.14709627,  0.32905504],
       [-0.28690474,  0.90271499,  0.26516538, -0.07354813,  0.16452752],[-0.44367825, -0.3881998 ,  0.72286651,  0.36021819, -0.01254537],
       [-0.3549426 ,  0.90035112,  0.17579809,  0.18010909, -0.00627268]])

In [41]:
np.linalg.matrix_rank(checknull)

4

*Not same as rank is 4*