<a href="https://colab.research.google.com/github/mhaletoki/MA22C025_2023_PL/blob/main/Assignments/Assignment_5/row_swap_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def swaprow(i, j, A):
  tmp = A[i, :]
  A[i, :] = A[j, :]
  A[j, :] = tmp

In [ ]:
A = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

In [ ]:
print("Original Matrix:")
print(A)

Original Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
swaprow(0, 2, A)

print("Matrix after swapping rows:")
print(A)

Matrix after swapping rows:
[[0 0 1]
 [0 1 0]
 [0 0 1]]


In [ ]:
# the above code only copies the two compared rows so we construct another function to solve this problem

In [ ]:
def swap_rows(i, j, A):
    temp_2 = A[i, :].copy() #copy() is for modifying numpy array without altering the original data
    A[i, :] = A[j, :]
    A[j, :] = temp_2
    return A

In [ ]:
A = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
print(A)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
swap_rows(0,2,A)
print('The matrix after swapping rows becomes')
print(A)

The matrix after swapping rows becomes
[[0 0 1]
 [0 1 0]
 [1 0 0]]
